#!/usr/bin/env bash
#
# One-time setup for Trojan Errors (crash analytics) local development.
#
# Stands up the storage backend (Bugsink -- Sentry-protocol compatible, runs
# WITHOUT Docker), provisions the project + API token the Trojan shim uses, and
# writes crash-analytics/runtime.json with the values the shim reads at boot.
#
# Idempotent: safe to re-run. Takes ~2 minutes on a cold machine.
#
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUGSINK_DIR="$HERE/bugsink"
VENV="$BUGSINK_DIR/.venv"
RUNTIME_JSON="$HERE/runtime.json"

BUGSINK_VERSION="${BUGSINK_VERSION:-2.6.0}"
BUGSINK_PORT="${BUGSINK_PORT:-8000}"
ADMIN_USER="${BUGSINK_ADMIN_USER:-admin}"
ADMIN_EMAIL="${BUGSINK_ADMIN_EMAIL:-admin@trojan.local}"
ADMIN_PASSWORD="${BUGSINK_ADMIN_PASSWORD:-trojan-local-dev}"

say() { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
die() { printf '\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

# ── 1. Find a Python 3.11+ interpreter ────────────────────────────────────
# Bugsink needs a modern Python. macOS system Python (3.9, from Xcode) is too
# old, so we look for a real one. `uv` is preferred because it also handles the
# venv + installs an order of magnitude faster.
say "Locating a Python 3.11+ interpreter"
UV_BIN=""
for candidate in "$HOME/.local/bin/uv" "$(command -v uv 2>/dev/null || true)"; do
  if [ -n "$candidate" ] && [ -x "$candidate" ]; then UV_BIN="$candidate"; break; fi
done

# Probe newest-first, but actually execute each candidate -- a broken Homebrew
# Python that exists on PATH but can't run is common enough to be worth the
# extra exec (seen on the dev machine this was built on: python3.14 was
# installed but `platform.mac_ver()` returned empty).
PY_BIN=""
for candidate in python3.13 python3.12 python3.11 python3.14; do
  if command -v "$candidate" >/dev/null 2>&1 \
     && "$candidate" -c 'import platform,sys; assert platform.mac_ver()[0] or sys.platform!="darwin"' >/dev/null 2>&1; then
    PY_BIN="$(command -v "$candidate")"
    break
  fi
done

if [ -z "$UV_BIN" ] && [ -z "$PY_BIN" ]; then
  die "Need Python 3.11+ (or uv). Install with: brew install python@3.13"
fi

# ── 2. Create the virtualenv and install Bugsink ──────────────────────────
if [ ! -x "$VENV/bin/python" ]; then
  say "Creating virtualenv at crash-analytics/bugsink/.venv"
  if [ -n "$UV_BIN" ]; then
    "$UV_BIN" venv --python "${PY_BIN:-3.13}" "$VENV"
  else
    "$PY_BIN" -m venv "$VENV"
  fi
else
  say "Virtualenv already exists, reusing it"
fi

if ! "$VENV/bin/python" -c "import bugsink" >/dev/null 2>&1; then
  say "Installing bugsink==$BUGSINK_VERSION (this is the only heavy step)"
  if [ -n "$UV_BIN" ]; then
    "$UV_BIN" pip install --python "$VENV/bin/python" "bugsink==$BUGSINK_VERSION"
  else
    "$VENV/bin/python" -m pip install --quiet --upgrade pip
    "$VENV/bin/python" -m pip install --quiet "bugsink==$BUGSINK_VERSION"
  fi
else
  say "bugsink already installed, skipping"
fi

# ── 3. Generate the Bugsink config ────────────────────────────────────────
# bugsink-manage resolves DJANGO_SETTINGS_MODULE=bugsink_conf from the CWD, so
# everything below runs from $BUGSINK_DIR.
cd "$BUGSINK_DIR"

if [ ! -f "$BUGSINK_DIR/bugsink_conf.py" ]; then
  say "Generating bugsink_conf.py (template: local)"
  "$VENV/bin/bugsink-create-conf" \
    --template=local \
    --host localhost \
    --port "$BUGSINK_PORT" \
    -o "$BUGSINK_DIR/bugsink_conf.py" >/dev/null
else
  say "bugsink_conf.py already exists, leaving it alone"
fi

# ── 4. Migrate ────────────────────────────────────────────────────────────
say "Running database migrations"
"$VENV/bin/bugsink-manage" migrate --no-input >/dev/null

# ── 5. Admin user (needed to own the team/project) ────────────────────────
say "Ensuring admin user exists"
DJANGO_SUPERUSER_PASSWORD="$ADMIN_PASSWORD" \
  "$VENV/bin/bugsink-manage" createsuperuser \
  --no-input --username "$ADMIN_USER" --email "$ADMIN_EMAIL" >/dev/null 2>&1 \
  || say "  (admin user already present)"

# ── 6. Provision the Trojan project + read token ──────────────────────────
say "Provisioning Trojan project and API token"
PROVISION_OUT="$("$VENV/bin/bugsink-manage" shell < "$BUGSINK_DIR/provision.py")"
PROVISION_JSON="$(printf '%s\n' "$PROVISION_OUT" | grep '^TROJAN_PROVISION_JSON:' | sed 's/^TROJAN_PROVISION_JSON://')"

if [ -z "$PROVISION_JSON" ]; then
  printf '%s\n' "$PROVISION_OUT" >&2
  die "Provisioning failed -- see output above"
fi

# ── 7. Write runtime.json for the shim ────────────────────────────────────
say "Writing crash-analytics/runtime.json"
BUGSINK_PORT="$BUGSINK_PORT" PROVISION_JSON="$PROVISION_JSON" \
node -e '
  const fs = require("node:fs");
  const provisioned = JSON.parse(process.env.PROVISION_JSON);
  const port = process.env.BUGSINK_PORT;
  fs.writeFileSync(process.argv[1], JSON.stringify({
    _comment: "Generated by crash-analytics/setup.sh. Do not commit. Re-run setup.sh to regenerate.",
    backend: "bugsink",
    backendUrl: `http://localhost:${port}`,
    ...provisioned,
  }, null, 2) + "\n");
' "$RUNTIME_JSON"

say "Setup complete."
echo
echo "  Storage backend : Bugsink (no Docker) on http://localhost:$BUGSINK_PORT"
echo "  Bugsink admin   : $ADMIN_USER / $ADMIN_PASSWORD   (internal only -- customers never see this)"
echo "  Shim config     : crash-analytics/runtime.json"
echo
echo "Next: ./crash-analytics/start.sh"
