package normalizer

import "testing"

func TestIsNonShipping(t *testing.T) {
	tests := []struct {
		path string
		drop bool
	}{
		// Dependency dirs.
		{"node_modules/react/index.js", true},
		{"app/vendor/lib/foo.go", true},
		{"backend/.venv/lib/python3.11/site-packages/x.py", true},
		// Build output.
		{"dist/bundle.js", true},
		{"frontend/.next/server/page.js", true},
		{"target/classes/App.class", true},
		// Test scaffolding by dir.
		{"tests/test_login.py", true},
		{"src/__tests__/button.tsx", true},
		{"internal/testdata/fixture.go", true},
		// Test/generated by filename beside prod code.
		{"internal/normalizer/dedup_test.go", true},
		{"src/api/users.test.ts", true},
		{"src/api/users.spec.js", true},
		{"pkg/service_generated.go", true},
		{"proto/user.pb.go", true},
		{"public/app.min.js", true},
		// Shipping code — kept.
		{"main.go", false},
		{"internal/ai/triage.go", false},
		{"src/api/users.ts", false},
		{"app/handlers/auth.py", false},
		{"./cmd/trojan/main.go", false},
		// A dir literally containing "test" as a substring is NOT a test dir.
		{"src/greatestapp/index.js", false},
		{"src/attestation/verify.go", false},
	}
	for _, tt := range tests {
		if got := isNonShipping(tt.path); got != tt.drop {
			t.Errorf("isNonShipping(%q) = %v, want %v", tt.path, got, tt.drop)
		}
	}
}

func TestFilterPaths(t *testing.T) {
	in := []Finding{
		{ID: "1", FilePath: "main.go", LineNumber: 10},
		{ID: "2", FilePath: "node_modules/x/y.js", LineNumber: 5},
		{ID: "3", FilePath: "internal/normalizer/dedup_test.go", LineNumber: 1},
		{ID: "4", FilePath: "", LineNumber: 0}, // DAST/host-level, no path -> kept
		{ID: "5", FilePath: "src/api/users.ts", LineNumber: 20},
	}
	kept, dropped := FilterPaths(in)
	if dropped != 2 {
		t.Errorf("dropped = %d, want 2", dropped)
	}
	gotIDs := []string{}
	for _, f := range kept {
		gotIDs = append(gotIDs, f.ID)
	}
	want := []string{"1", "4", "5"}
	if len(gotIDs) != len(want) {
		t.Fatalf("kept IDs = %v, want %v", gotIDs, want)
	}
	for i := range want {
		if gotIDs[i] != want[i] {
			t.Fatalf("kept IDs = %v, want %v", gotIDs, want)
		}
	}
}
